### ISSUE TITLE
关于g2o和ceres的区别

### ISSUE THREAD

**Issue by XinnWang** [guisongchen/slam_test#2]
您好，感谢您的分享。
我在尝试使用ceres代替g2o的过程中发现，对于相同的输入，两者的优化结果差异很大，有时候g2o的结果更好，有时候ceres的结果更好。此外，还发现ceres对位置的调整力度比g2o更大，导致ceres的尺度更不稳定。请问一下您是否发现了类似的问题呢？

**Comment by guisongchen** [comment]
我没有进行过相关的对比测试，所以没有办法给出回答。
相同的数据输入，优化结果不同，可能的原因有很多。因为不了解你面临的具体情况，建议可以从以下几个方面分析：
1. 两者的cost function是否相同。
2. 两者采用的使用的求解器类型是否相同。
3. 如果使用了loss function，两者的函数类型是否相同，参数配置是否相同。
4. 两者的收敛判定条件是否相同。
